# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  public_directory: '%kernel.project_dir%/public'
  uploads_directory: '%public_directory%/upload/'
  video_handler:
    save_path: '%public_directory%/upload/resize/'
    watermark:
      - image_path: '%public_directory%/upload/images/watermark.png'
        coordinates:
          x: main_w-overlay_w-30
          y: main_h-overlay_h-30
          position: absolute
      - image_path: '%public_directory%/upload/images/watermark_center.png'
        coordinates:
          x: (main_w-overlay_w)/2
          y: (main_h-overlay_h)/2
          position: absolute
    size:
      240:
        width: 426
        height: 240
      360:
        width: 640
        height: 360
      480:
        width: 854
        height: 480
      720:
        width: 1280
        height: 720
      1080:
        width: 1920
        height: 1080

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
  file_uploader.default:
    class: App\Service\File\FileUploader
    arguments:
      $publicPath: '%public_directory%'
      $uploadPath: '%uploads_directory%'

  file_uploader.resize:
    class: App\Service\File\FileUploader
    public: true
    arguments:
      $publicPath: '%public_directory%'
      $uploadPath: '%uploads_directory%resize/'
  App\Service\File\FileUploader: '@file_uploader.default'
