version: "3.4"

services:
  php:
    build: conf/php
    volumes:
      - ./backend:/app:cached
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:cached
      - ./conf/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./conf/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    working_dir: /app
    env_file:
      - .env
  nginx:
    image: nginx
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend:/app:cached
    ports:
      - "80:80"
  db:
    image: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
